@baseUrl = http://localhost:2000/api

# Auth

# @name register
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
    "email": "jinnguyen054@gmail.com",
    "password": "2604",
    "name": "Syaoran"
}

###

# @name login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
    "email": "jinnguyen054@gmail.com",
    "password": "2604"
}

### 

# @name [Auth]refreshToken
POST {{baseUrl}}/auth/refresh-token

### 

# @name [Auth]logout
GET {{baseUrl}}/auth/logout

### 

# @name [Auth]loginByRefreshToken
POST {{baseUrl}}/auth/login-refresh
